[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
for i = 1, #G.jokers.cards do
    if G.jokers.cards[i].ability.name == 'Joker Stencil' then self.ability.x_mult = self.ability.x_mult + 1 end
end
'''
position = "at"
payload = '''
self.ability.x_mult = BalatroFusion.get_gap_count_for_card_area({{ location = "jokers", type = "joker" }})
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
if (G.jokers.config.card_limit - #G.jokers.cards) > 0 then
'''
position = "at"
payload = '''
if BalatroFusion.get_gap_count_for_card_area({{ location = "jokers", type = "joker" }}) > 1 then
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
if self.ability.name == 'Fibonacci' and (
context.other_card:get_id() == 2 or 
context.other_card:get_id() == 3 or 
context.other_card:get_id() == 5 or 
context.other_card:get_id() == 8 or 
context.other_card:get_id() == 14) then
'''
position = "at"
payload = '''
if self.ability.name == 'Fibonacci' and BalatroFusion.check_fibonacci_rank(context.other_card) then
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
if flags.booster_create_flags then
    card = SMODS.create_card(flags.booster_create_flags)
end
'''
position = "at"
payload = '''
if flags and flags.booster_create_flags then
    local f = flags.booster_create_flags
    card = create_card(f.card_type, G.pack_cards, nil, nil, true, f.soulable, f.forced_key, f.key_append)
    
    if f.card_type and f.card_type == "Enhanced" or f.card_type == "Base" then
        local edition_rate = 2
        local edition = poll_edition('standard_edition'..G.GAME.round_resets.ante, edition_rate, true)
        card:set_edition(edition)
        card:set_seal(SMODS.poll_seal({mod = 10}), true, true)
    end
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
if self.highlighted ~= true then 
    self.area:add_to_highlighted(self)
else
    self.area:remove_from_highlighted(self)
    play_sound('cardSlide2', nil, 0.3)
end
'''
position = "at"
payload = '''
if self.highlighted ~= true then 
    if self.area == G.hand then
        BalatroFusion.adjust_play_limits(self, 1)
    end
    self.area:add_to_highlighted(self)
else
    if self.area == G.hand then
        BalatroFusion.adjust_play_limits(self, -1)
    end
    self.area:remove_from_highlighted(self)
    play_sound('cardSlide2', nil, 0.3)
end
'''
match_indent = true


[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
SMODS.calculate_context({discard = true, other_card =  G.hand.highlighted[i], full_hand = G.hand.highlighted, ignore_other_debuff = true}, effects)
'''
position = "before"
payload = '''
BalatroFusion.adjust_play_limits(G.hand.highlighted[i], -1)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
if G.hand.highlighted[i]:is_face() then inc_career_stat('c_face_cards_played', 1) end
'''
position = "before"
payload = '''
BalatroFusion.adjust_play_limits(G.hand.highlighted[i], -1)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''
e.config.ref_table:use_consumeable(area)
'''
position = "at"
payload = '''
for _, v in ipairs(G.hand.highlighted) do
    BalatroFusion.adjust_play_limits(v, -1)
end
e.config.ref_table:use_consumeable(area)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
if self.ability.effect == "Lucky Card" then
'''
position = "at"
payload = '''
if BalatroFusion.check_lucky_card(self) then
'''
match_indent = true


[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
local suits = {
    ['Hearts'] = 0,
    ['Diamonds'] = 0,
    ['Spades'] = 0,
    ['Clubs'] = 0
}
for i = 1, #context.scoring_hand do
    if not SMODS.has_any_suit(context.scoring_hand[i]) then
        if context.scoring_hand[i]:is_suit('Hearts', true) and suits["Hearts"] == 0 then suits["Hearts"] = suits["Hearts"] + 1
        elseif context.scoring_hand[i]:is_suit('Diamonds', true) and suits["Diamonds"] == 0  then suits["Diamonds"] = suits["Diamonds"] + 1
        elseif context.scoring_hand[i]:is_suit('Spades', true) and suits["Spades"] == 0  then suits["Spades"] = suits["Spades"] + 1
        elseif context.scoring_hand[i]:is_suit('Clubs', true) and suits["Clubs"] == 0  then suits["Clubs"] = suits["Clubs"] + 1 end
    end
end
for i = 1, #context.scoring_hand do
    if SMODS.has_any_suit(context.scoring_hand[i]) then
        if context.scoring_hand[i]:is_suit('Hearts') and suits["Hearts"] == 0 then suits["Hearts"] = suits["Hearts"] + 1
        elseif context.scoring_hand[i]:is_suit('Diamonds') and suits["Diamonds"] == 0  then suits["Diamonds"] = suits["Diamonds"] + 1
        elseif context.scoring_hand[i]:is_suit('Spades') and suits["Spades"] == 0  then suits["Spades"] = suits["Spades"] + 1
        elseif context.scoring_hand[i]:is_suit('Clubs') and suits["Clubs"] == 0  then suits["Clubs"] = suits["Clubs"] + 1 end
    end
end
if suits["Hearts"] > 0 and
suits["Diamonds"] > 0 and
suits["Spades"] > 0 and
suits["Clubs"] > 0 then
'''
position = "at"
payload = '''
if BalatroFusion.check_flower_pot_suits(context.scoring_hand) then
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
self.lucky_trigger = true
ret = ret + self.ability.mult
'''
position = "at"
payload = '''
self.lucky_trigger = true
ret = ret + BalatroFusion.get_lucky_reward(self, "mult") 
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
self.lucky_trigger = true
ret = ret +  self.ability.p_dollars
'''
position = "at"
payload = '''
self.lucky_trigger = true
ret = ret + BalatroFusion.get_lucky_reward(self, "dollars")
'''
match_indent = true
