-- SMODS.BalatroFusion.Fusion:new_generic({
--     id = "joker_fusion",
--     key = "teal",
--     name = "Teal Joker",
--     input = {
--         "j_blue_joker",
--         "j_green_joker",
--     },
--     output = "j_bfs_teal_joker"
-- })

-- SMODS.Joker {
--     key = "teal_joker",
--     name = "Teal Joker",
--     config = {
--         extra = {
--             mult_mod = 0.5,
--             mult = 0
--         }
--     },
--     pos = { x = 7, y = 0 },
--     cost = 9,
--     rarity = "bfs_fused",
--     blueprint_compat = true,
--     atlas = "joker",
--     loc_vars = function(self, info_queue, card)
--         return {
--             vars = {
--                 card.ability.extra.mult_mod,
--                 card.ability.extra.mult
--             }
--         }
--     end,
--     calculate = function(self, card, context)
--         if context.joker_main then
--             return {
--                 mult = card.ability.extra.mult
--             }
--         end
--         if context then
--             card.ability.extra.mult = card.ability.extra.mult + (card.ability.extra.mult_mod * #G.deck.cards)
--         end
--     end,
-- 	bfs_credits = {
-- 		code = { "Glitchkat10" }
-- 	}
-- }